version: '3.8'

services:
  server:
    build: .
    image: jota-transcriber:latest
    container_name: jota-transcriber
    network_mode: host
    env_file:
      - .env
    volumes:
      - ./models:/app/models
      # Mount SSL certs if needed
      # - ./server.crt:/app/server.crt
      # - ./server.key:/app/server.key
    restart: unless-stopped
    # Enable GPU support
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
