name: Semantic Release

on:
  push:
    branches:
      - main # Se ejecuta tras el squash merge en la rama principal

jobs:
  release:
    name: Release and Changelog
    runs-on: ubuntu-latest
    permissions:
      contents: write 
      issues: write
      pull-requests: write

    steps:
      - name: Generate Token from Jota-App
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }} # Identidad de la App
          
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 
          # Importante: Usar el token para que el checkout configure la identidad
          token: ${{ secrets.RELEASE_TOKEN }} 

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install Semantic Release dependencies
        run: |
          npm install -g semantic-release \
          @semantic-release/changelog \
          @semantic-release/git \
          @semantic-release/github

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: npx semantic-release